system('defaults write org.R-project.R force.LANG en_US.UTF-8')
install.packages("data.table")
install.packages("urltools")
install.packages("stringr")
install.packages("bit64")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("lubridate")
install.packages("scales")
install.packages("zoo")
install.packages("pryr")
install.packages("sas7bdat")
install.packages("keras")
install.packages("neuralnet")
install.packages("randomForest")
install.packages("rpart")
install.packages("boot")
install.packages("caret")
install.packages("nnet")
install.packages("xgboost")
# install.packages("tfestimators")
# install.packages("tensorflow")
# install.packages("xlsx")
install.packages("ggvis")
install.packages("shiny")
# install.packages("RODBC")
install.packages("jsonlite")
install.packages("pdftools")
